yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views


app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path(
        'profile/<str:username>/edit/', views.profile_edit, name='profile_edit'
    ),
    path("profile/<str:username>/follow/", views.profile_follow,
         name="profile_follow"),
    path("profile/<str:username>/unfollow/", views.profile_unfollow,
         name="profile_unfollow"),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path("follow/", views.follow_index, name="follow_index"),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

handler404 = "posts.views.page_not_found"
handler500 = "posts.views.server_error"
handler403 = "posts.views.permission_denied"

yatube/templates/includes/create-one-post.html
{% load thumbnail %}
<article>
  <ul>
    <li>
      Автор: {{ post.author.username }}
      <a class="btn btn-sm btn-primary"
         href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img src="{{ im.url }}">
    {% endthumbnail %}
  </ul>
  <p>{{ post.text }}</p>
  <a class="btn btn-sm btn-primary"
     href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
  {% if post.comments.exists %}
    <div>
      Комментариев: {{ post.comments.count }}
    </div>
    <div>
      {{ post.comments.first }}
    </div>
  {% endif %}
  {% if post.group and button %}
    <a class="btn btn-sm btn-primary"
       href="{% url 'posts:group_list' post.group.slug %}"
    >все записи группы</a>
  {% endif %}
  {% if not forloop.last %}
    <hr>{% endif %}
</article>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/form_base.html
{% load user_filters %}
{% csrf_token %}
{% if form.non_field_errors %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}
{% for field in form %}
  <div class="form-group row my-3 p-3"
          {% if field.field.required %}
       aria-required="true"
          {% else %}
       aria-required="false"
          {% endif %}
  >
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
      {% if field.field.required %}
        <span class="required text-danger">*</span>
      {% endif %}
    </label>
    {{ field|addclass:'form-control' }}
    {% if field.errors %}
      {% for error in field.errors %}
        <div class="alert alert-danger">
          {{ error|escape }}
        </div>
      {% endfor %}
    {% endif %}
    {% if field.help_text %}
      <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
        {{ field.help_text }}
      </small>
    {% endif %}
  </div>
{% endfor %}

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30"
             class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      <ul class="nav nav-pills">
        {% with request.resolver_match.view_name as view_name %}
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.view_name  == 'posts:follow_index' %}
            active
            {% endif %}" href="{% url 'posts:follow_index' %}">Лента
                подписок</a>
            </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.view_name  == 'about:author' %}
          active
          {% endif %}" href="{% url 'about:author' %}">Об авторе</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.view_name  == 'about:tech' %}
          active
          {% endif %}" href="{% url 'about:tech' %}">Технологии</a>
          </li>
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link {% if request.resolver_match.view_name  == 'posts:post_create' %}
          active
          {% endif %}" href="{% url 'posts:post_create' %}">Новая запись</a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light {% if request.resolver_match.view_name  == 'users:password_change' %}
          active
          {% endif %}" href="{% url 'users:password_change' %}">Изменить
                пароль</a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light {% if request.resolver_match.view_name  == 'posts:profile_edit' %}
          active
          {% endif %}"
                 href="{% url 'posts:profile_edit' request.user.username %}">Изменить
                профиль</a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light {% if request.resolver_match.view_name  == 'users:logout' %}
          active
          {% endif %}" href="{% url 'users:logout' %}">Выйти</a>
            </li>
            <li>
              <a class="nav-link"
                 href="{% url 'posts:profile' request.user.username %}">{{ user.username }}</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link link-light {% if request.resolver_match.view_name  == 'users:login' %}
          active
          {% endif %}" href="{% url 'users:login' %}">Войти</a>
            </li>
            <li class="nav-item">
              <a class="nav-link link-light {% if request.resolver_match.view_name  == 'users:signup' %}
          active
          {% endif %}" href="{% url 'users:signup' %}">Регистрация</a>
            </li>
          {% endif %}
        {% endwith %}
      </ul>
    </div>
  </nav>
</header>

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Предыдущая
          </a>
        </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Следующая
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

yatube/templates/includes/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}